---
all:
  children:
    pcs_servers:
       hosts:
         pcs1:
           ansible_host: "192.168.56.201"
           ansible_private_key_file: ".vagrant/machines/pcs1/virtualbox/private_key"
         pcs2:
           ansible_host: "192.168.56.202"
           ansible_private_key_file: ".vagrant/machines/pcs2/virtualbox/private_key"        
         pcs3:
           ansible_host: "192.168.56.203"
           ansible_private_key_file: ".vagrant/machines/pcs3/virtualbox/private_key"      
       vars:
         virtualbox_host: "192.168.56.1"
         virtualbox_host_username: "mbfx"
         virtualbox_host_password: "strong_pass"
    iscsi_server:
      hosts:
        iscsi:
          ansible_host: "192.168.56.204"
          ansible_private_key_file: ".vagrant/machines/iscsi/virtualbox/private_key"
    database:
      hosts:
        db:
          ansible_host: "192.168.56.205"
          ansible_private_key_file: ".vagrant/machines/db/virtualbox/private_key"
    nginx_server:
      hosts:
        nginx1:
          ansible_host: "192.168.57.100"
          ansible_private_key_file: ".vagrant/machines/nginx1/virtualbox/private_key"
        nginx2:
          ansible_host: "192.168.57.101"
          ansible_private_key_file: ".vagrant/machines/nginx2/virtualbox/private_key"

  vars:
    domain: "mydomain.test"
    ntp_timezone: "UTC"
    pcs_password: "strong_pass" # cluster user: hacluster
    cluster_name: "hacluster"
    iqn_server: "iqn.2024-01.ru.otus:storage.target00"
    wwn_client1: "iqn.2024-01.ru.otus:storage.client201"
    wwn_client2: "iqn.2024-01.ru.otus:storage.client202"
    wwn_client3: "iqn.2024-01.ru.otus:storage.client203"
...
